In [1]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def relu(x):
    return np.maximum(0, x)

def forward_propagation(X, weights, biases, activations):
    """
    Performs forward propagation through a neural network.

    Args:
        X (numpy.ndarray): Input data (input_dim, num_samples).
        weights (list): List of weight matrices for each layer.
        biases (list): List of bias vectors for each layer.
        activations (list): List of activation functions for each layer ('sigmoid' or 'relu').

    Returns:
        numpy.ndarray: Output of the network (output_dim, num_samples).
        dict: Dictionary containing 'Z' (linear outputs) and 'A' (activated outputs) for each layer.
    """
    num_layers = len(weights)
    A = X
    cache = {'A': [A]}

    for l in range(num_layers):
        W_l = weights[l]
        b_l = biases[l]
        activation_l = activations[l]

        Z_l = np.dot(W_l, A) + b_l

        if activation_l == 'sigmoid':
            A = sigmoid(Z_l)
        elif activation_l == 'relu':
            A = relu(Z_l)
        else:
            raise ValueError(f"Unsupported activation function: {activation_l}")

        cache['Z'] = cache.get('Z', []) + [Z_l]
        cache['A'] = cache.get('A', []) + [A]

    return A, cache

# Example Usage:
# Define network architecture
input_dim = 2
hidden_layer_1_dim = 4
hidden_layer_2_dim = 3
output_dim = 1

# Initialize random weights and biases for demonstration
np.random.seed(42)
weights = [
    np.random.randn(hidden_layer_1_dim, input_dim) * 0.01,  # Layer 1 weights
    np.random.randn(hidden_layer_2_dim, hidden_layer_1_dim) * 0.01, # Layer 2 weights
    np.random.randn(output_dim, hidden_layer_2_dim) * 0.01   # Output layer weights
]

biases = [
    np.zeros((hidden_layer_1_dim, 1)), # Layer 1 biases
    np.zeros((hidden_layer_2_dim, 1)), # Layer 2 biases
    np.zeros((output_dim, 1))         # Output layer biases
]

activations = ['relu', 'relu', 'sigmoid'] # Activation functions for each layer

# Generate some sample input data (num_features, num_samples)
X_sample = np.array([[0.1, 0.5, 0.3], [0.8, 0.2, 0.7]]) # 2 features, 3 samples

# Perform forward propagation
output, layer_outputs = forward_propagation(X_sample, weights, biases, activations)

print("Input X:\n", X_sample)
print("\nOutput of the network:\n", output)
print("\nLinear outputs (Z) for each layer:")
for i, z in enumerate(layer_outputs['Z']):
    print(f"  Layer {i+1} Z:\n{z}")
print("\nActivated outputs (A) for each layer:")
for i, a in enumerate(layer_outputs['A']):
    if i > 0: # Skip input A
        print(f"  Layer {i} A:\n{a}")

Input X:
 [[0.1 0.5 0.3]
 [0.8 0.2 0.7]]

Output of the network:
 [[0.50000012 0.5        0.50000007]]

Linear outputs (Z) for each layer:
  Layer 1 Z:
[[-0.0006094   0.00220704  0.00052229]
 [ 0.01283193  0.0062845   0.01260427]
 [-0.00210725 -0.00163904 -0.00234142]
 [ 0.00771869  0.00943093  0.01010968]]
  Layer 2 Z:
[[ 3.36726719e-05 -2.01869622e-05  1.88499340e-05]
 [-2.88911967e-04 -1.67928897e-04 -2.96736824e-04]
 [-6.86873642e-05 -1.35798152e-04 -1.08460749e-04]]
  Layer 3 Z:
[[4.93523101e-07 0.00000000e+00 2.76273826e-07]]

Activated outputs (A) for each layer:
  Layer 1 A:
[[0.         0.00220704 0.00052229]
 [0.01283193 0.0062845  0.01260427]
 [0.         0.         0.        ]
 [0.00771869 0.00943093 0.01010968]]
  Layer 2 A:
[[3.36726719e-05 0.00000000e+00 1.88499340e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]]
  Layer 3 A:
[[0.50000012 0.5        0.50000007]]
