<a href="https://colab.research.google.com/github/NischalBhusal/Machine-Learning/blob/main/MLDAY_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Numpy Revision Today and reading HOML
import numpy as np

arr = np.array([1,2,3])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3]


In [ ]:
# 2D and 3D
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
# tensor
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# np.arange which is like a range
np.arange(1,11)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
# np.ones and np.zeros
np.ones((3,4))
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# np.random
np.random.random((3,4))

array([[0.67360984, 0.07813049, 0.28779512, 0.55607702],
       [0.30891044, 0.24551758, 0.12552894, 0.38208159],
       [0.35215908, 0.17944075, 0.35807656, 0.28963992]])

In [ ]:
# np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr3.ndim

3

In [ ]:
print(arr3.shape)
arr3

(2, 2, 2)


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
print(arr2.size)
arr2

6


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(arr3.dtype)
arr3

int64


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
arr3.itemsize

8

In [ ]:
# astype
arr3.astype(np.int32)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)

In [ ]:
#reshape
